<template>
  <div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <svg
            id="floor1"
            width="100%"
            height="100%"
            x="605"
            y="270"
            overflow="visible"
            xmlns="http://www.w3.org/2000/svg"
            xmlns:se="http://svg-edit.googlecode.com"
            xmlns:xlink="http://www.w3.org/1999/xlink"
            viewBox="0 0 600 440"
          >
            <!-- Created with SVG-edit - http://svg-edit.googlecode.com/ -->
            <g style="pointer-events:all" stroke="none" fill="#000000" stroke-width="1px">
              <title
                style="pointer-events:inherit"
                stroke="none"
                fill="#000000"
                stroke-width="1px"
              >Floor 1</title>
              <rect
                fill="#aaffff"
                stroke="#000000"
                stroke-width="0px"
                x="138"
                y="137"
                width="92"
                height="92"
                id="floor_1_service"
                fill-opacity="1"
                stroke-opacity="1"
              />
              <rect
                class="cursor-pointer"
                fill="#bfbfbf"
                stroke="#000000"
                stroke-width="0px"
                x="138"
                y="237"
                width="92"
                height="92"
                id="floor_1_m04"
                fill-opacity="1"
                stroke-opacity="1"
                v-on:click="selectRoom(txtFloor1.roomM04)"
              />
              <rect
                class="cursor-pointer"
                fill="#bfbfbf"
                stroke="#000000"
                stroke-width="0px"
                x="138"
                y="337"
                width="92"
                height="92"
                id="floor_1_m03"
                fill-opacity="1"
                stroke-opacity="1"
                v-on:click="selectRoom(txtFloor1.roomM03)"
              />
              <rect
                class="cursor-pointer"
                fill="#bfbfbf"
                stroke="#000000"
                stroke-width="0px"
                x="437"
                y="137"
                width="92"
                height="92"
                id="floor_1_m23"
                fill-opacity="1"
                stroke-opacity="1"
                v-on:click="selectRoom(txtFloor1.roomM23)"
              />
              <rect
                class="cursor-pointer"
                fill="#bfbfbf"
                stroke="#000000"
                stroke-width="0px"
                x="437"
                y="237"
                width="92"
                height="92"
                id="floor_1_m22"
                fill-opacity="1"
                stroke-opacity="1"
                v-on:click="selectRoom(txtFloor1.roomM22)"
              />
              <rect
                class="cursor-pointer"
                fill="#bfbfbf"
                stroke="#000000"
                stroke-width="0px"
                x="437"
                y="337"
                width="92"
                height="92"
                id="floor_1_m21"
                fill-opacity="1"
                stroke-opacity="1"
                v-on:click="selectRoom(txtFloor1.roomM21)"
              />
              <rect
                class="cursor-pointer"
                fill="#bfbfbf"
                stroke="#000000"
                stroke-width="0px"
                x="290"
                y="250"
                width="45"
                height="45"
                fill-opacity="1"
                stroke-opacity="1"
                id="floor_1_m14"
                v-on:click="selectRoom(txtFloor1.roomM14)"
              />
              <rect
                class="cursor-pointer"
                fill="#bfbfbf"
                stroke="#000000"
                stroke-width="0px"
                x="342"
                y="250"
                width="45"
                height="45"
                fill-opacity="1"
                stroke-opacity="1"
                id="floor_1_m18"
                v-on:click="selectRoom(txtFloor1.roomM18)"
              />
              <rect
                class="cursor-pointer"
                fill="#bfbfbf"
                stroke="#000000"
                stroke-width="0px"
                x="290"
                y="300"
                width="45"
                height="45"
                fill-opacity="1"
                stroke-opacity="1"
                id="floor_1_m13"
                v-on:click="selectRoom(txtFloor1.roomM13)"
              />
              <rect
                class="cursor-pointer"
                fill="#bfbfbf"
                stroke="#000000"
                stroke-width="0px"
                x="342"
                y="300"
                width="45"
                height="45"
                fill-opacity="1"
                stroke-opacity="1"
                id="floor_1_m17"
                v-on:click="selectRoom(txtFloor1.roomM17)"
              />
              <rect
                class="cursor-pointer"
                fill="#bfbfbf"
                stroke="#000000"
                stroke-width="0px"
                x="290"
                y="350"
                width="45"
                height="45"
                fill-opacity="1"
                stroke-opacity="1"
                id="floor_1_m12"
                v-on:click="selectRoom(txtFloor1.roomM12)"
              />
              <rect
                class="cursor-pointer"
                fill="#bfbfbf"
                stroke="#000000"
                stroke-width="0px"
                x="342"
                y="350"
                width="45"
                height="45"
                fill-opacity="1"
                stroke-opacity="1"
                id="floor_1_m16"
                v-on:click="selectRoom(txtFloor1.roomM16)"
              />
              <rect
                class="cursor-pointer"
                fill="#bfbfbf"
                stroke="#000000"
                stroke-width="0px"
                x="138"
                y="37"
                width="92"
                height="92"
                fill-opacity="1"
                stroke-opacity="1"
                id="floor_1_111"
                v-on:click="selectRoom(txtFloor1.room111)"
              />
              <rect
                class="cursor-pointer"
                fill="#bfbfbf"
                stroke="#000000"
                stroke-width="0px"
                x="37"
                y="37"
                width="92"
                height="92"
                fill-opacity="1"
                stroke-opacity="1"
                id="floor_1_auditorium"
                v-on:click="selectRoom(txtFloor1.auditorium)"
              />
              <text
                fill="#000000"
                stroke="#000000"
                stroke-width="0px"
                stroke-dasharray="null"
                stroke-linejoin="null"
                stroke-linecap="null"
                x="184"
                y="220"
                id="txt_service"
                text-anchor="middle"
                xml:space="preserve"
                fill-opacity="1"
                stroke-opacity="1"
                v-text="txtFloor1.roomService"
              />
              <text
                fill="#000000"
                stroke="#000000"
                stroke-width="0px"
                stroke-dasharray="null"
                stroke-linejoin="null"
                stroke-linecap="null"
                x="184"
                y="320"
                text-anchor="middle"
                xml:space="preserve"
                fill-opacity="1"
                stroke-opacity="1"
                id="txt_m04"
                v-text="txtFloor1.roomM04"
              />
              <text
                fill="#000000"
                stroke="#000000"
                stroke-width="0px"
                stroke-dasharray="null"
                stroke-linejoin="null"
                stroke-linecap="null"
                x="184"
                y="420"
                text-anchor="middle"
                xml:space="preserve"
                fill-opacity="1"
                stroke-opacity="1"
                id="txt_m03"
                v-text="txtFloor1.roomM03"
              />
              <text
                fill="#000000"
                stroke="#000000"
                stroke-width="0px"
                stroke-dasharray="null"
                stroke-linejoin="null"
                stroke-linecap="null"
                x="485"
                y="220"
                text-anchor="middle"
                xml:space="preserve"
                fill-opacity="1"
                stroke-opacity="1"
                id="txt_m23"
                v-text="txtFloor1.roomM23"
              />
              <text
                fill="#000000"
                stroke="#000000"
                stroke-width="0px"
                stroke-dasharray="null"
                stroke-linejoin="null"
                stroke-linecap="null"
                x="484"
                y="320"
                text-anchor="middle"
                xml:space="preserve"
                fill-opacity="1"
                stroke-opacity="1"
                id="txt_m22"
                v-text="txtFloor1.roomM22"
              />
              <text
                fill="#000000"
                stroke="#000000"
                stroke-width="0px"
                stroke-dasharray="null"
                stroke-linejoin="null"
                stroke-linecap="null"
                x="484"
                y="420"
                text-anchor="middle"
                xml:space="preserve"
                fill-opacity="1"
                stroke-opacity="1"
                id="txt_m21"
                v-text="txtFloor1.roomM21"
              />
              <text
                fill="#000000"
                stroke="#000000"
                stroke-width="0px"
                stroke-dasharray="null"
                stroke-linejoin="null"
                stroke-linecap="null"
                x="184"
                y="120"
                text-anchor="middle"
                xml:space="preserve"
                fill-opacity="1"
                stroke-opacity="1"
                id="txt_111"
                v-text="txtFloor1.room111"
              />
              <text
                fill="#000000"
                stroke="#000000"
                stroke-width="0px"
                stroke-dasharray="null"
                stroke-linejoin="null"
                stroke-linecap="null"
                x="83"
                y="120"
                text-anchor="middle"
                xml:space="preserve"
                fill-opacity="1"
                stroke-opacity="1"
                id="txt_auditorium"
                v-text="txtFloor1.auditorium"
              />
              <text
                fill="#000000"
                stroke="#000000"
                stroke-width="0px"
                stroke-dasharray="null"
                stroke-linejoin="null"
                stroke-linecap="null"
                x="313"
                y="290"
                text-anchor="middle"
                xml:space="preserve"
                fill-opacity="1"
                stroke-opacity="1"
                id="txt_m14"
                v-text="txtFloor1.roomM14"
              />
              <text
                fill="#000000"
                stroke="#000000"
                stroke-width="0px"
                stroke-dasharray="null"
                stroke-linejoin="null"
                stroke-linecap="null"
                x="313"
                y="390"
                text-anchor="middle"
                xml:space="preserve"
                fill-opacity="1"
                stroke-opacity="1"
                id="txt_m12"
                v-text="txtFloor1.roomM12"
              />
              <text
                fill="#000000"
                stroke="#000000"
                stroke-width="0px"
                stroke-dasharray="null"
                stroke-linejoin="null"
                stroke-linecap="null"
                x="313"
                y="340"
                text-anchor="middle"
                xml:space="preserve"
                fill-opacity="1"
                stroke-opacity="1"
                id="txt_m13"
                v-text="txtFloor1.roomM13"
              />
              <text
                fill="#000000"
                stroke="#000000"
                stroke-width="0px"
                stroke-dasharray="null"
                stroke-linejoin="null"
                stroke-linecap="null"
                x="364"
                y="290"
                text-anchor="middle"
                xml:space="preserve"
                fill-opacity="1"
                stroke-opacity="1"
                id="txt_m18"
                v-text="txtFloor1.roomM18"
              />
              <text
                fill="#000000"
                stroke="#000000"
                stroke-width="0px"
                stroke-dasharray="null"
                stroke-linejoin="null"
                stroke-linecap="null"
                x="364"
                y="390"
                text-anchor="middle"
                xml:space="preserve"
                fill-opacity="1"
                stroke-opacity="1"
                id="txt_m16"
                v-text="txtFloor1.roomM16"
              />
              <text
                fill="#000000"
                stroke="#000000"
                stroke-width="0px"
                stroke-dasharray="null"
                stroke-linejoin="null"
                stroke-linecap="null"
                x="364"
                y="340"
                text-anchor="middle"
                xml:space="preserve"
                fill-opacity="1"
                stroke-opacity="1"
                id="txt_m17"
                v-text="txtFloor1.roomM17"
              />
            </g>
          </svg>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "Floor1",
  data() {
    return {
      txtFloor1: {
        auditorium: "Auditorium",
        room111: "111",
        roomService: "Service",
        roomM03: "M03",
        roomM04: "M04",
        roomM12: "M12",
        roomM13: "M13",
        roomM14: "M14",
        roomM16: "M16",
        roomM17: "M17",
        roomM18: "M18",
        roomM21: "M21",
        roomM22: "M22",
        roomM23: "M23"
      }
    };
  },
  methods: {
    selectRoom(name) {
      this.$parent.selectRoom(name);
    }
  }
};
</script>

<style scoped>
.cursor-pointer {
  cursor: pointer;
}

rect:hover {
  stroke-width: 2;
  stroke: #01579b;
}
</style>